# Expected runtime: 5-15 min (downloads ~2GB COCO subset on first run)
# Tested on: Colab T4 / local CPU
"""
data_loader.py — COCO subset loading, filtering, and augmentation pipeline.

This module handles:
1. Downloading a subset of COCO 2017 (train + val splits)
2. Filtering to keep only specified object categories
3. Converting COCO annotations to YOLO format (normalized xywh)
4. Applying Albumentations augmentations with bbox-safe transforms
5. Creating the directory structure expected by Ultralytics YOLOv8

Design decision: We use COCO categories as *proxies* for product defect types.
In a production system you would replace this with a real defect dataset (e.g.,
MVTec AD), but COCO gives us a free, well-annotated benchmark that runs on Colab.
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Any

import albumentations as A
import cv2
import numpy as np
import yaml
from pycocotools.coco import COCO
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
COCO_TRAIN_IMAGES_URL = "http://images.cocodataset.org/zips/train2017.zip"
COCO_VAL_IMAGES_URL = "http://images.cocodataset.org/zips/val2017.zip"
COCO_TRAIN_ANN_URL = (
    "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
)

YOLO_DATASET_YAML_TEMPLATE = """
# Auto-generated by data_loader.py
path: {dataset_root}
train: images/train
val: images/val

nc: {num_classes}
names: {class_names}
"""


def load_config(config_path: str = "configs/default.yaml") -> dict[str, Any]:
    """Load YAML configuration file.

    Args:
        config_path: Path to the YAML config file.

    Returns:
        Dictionary containing all configuration parameters.
    """
    config_path = Path(config_path)
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
    return config


def build_augmentation_pipeline(config: dict[str, Any]) -> A.Compose:
    """Build an Albumentations augmentation pipeline with bbox support.

    All transforms are bounding-box safe — they adjust bbox coordinates
    automatically. We use the 'yolo' format (normalized center x, y, w, h).

    Args:
        config: Dictionary containing augmentation parameters under the
                'augmentation' key.

    Returns:
        An Albumentations Compose object configured for YOLO-format bboxes.
    """
    aug_cfg = config["augmentation"]

    transform = A.Compose(
        [
            A.HorizontalFlip(p=aug_cfg["horizontal_flip_prob"]),
            A.VerticalFlip(p=aug_cfg["vertical_flip_prob"]),
            A.Rotate(
                limit=aug_cfg["rotation_limit"],
                border_mode=cv2.BORDER_CONSTANT,
                value=0,
                p=0.3,
            ),
            A.RandomBrightnessContrast(
                brightness_limit=aug_cfg["brightness_limit"],
                contrast_limit=aug_cfg["contrast_limit"],
                p=0.4,
            ),
            A.GaussianBlur(
                blur_limit=(3, aug_cfg["blur_limit"]),
                p=0.2,
            ),
            A.GaussNoise(
                var_limit=(0, aug_cfg["noise_var_limit"]),
                p=0.2,
            ),
            A.CLAHE(clip_limit=2.0, p=0.2),
        ],
        bbox_params=A.BboxParams(
            format="yolo",
            label_fields=["class_labels"],
            min_visibility=0.3,  # Drop bboxes that become <30% visible after aug
        ),
    )
    return transform


def get_coco_category_mapping(
    coco_api: COCO,
    target_categories: list[str],
) -> dict[int, int]:
    """Map COCO category IDs to contiguous 0-indexed class IDs.

    Args:
        coco_api: A pycocotools COCO object loaded with annotations.
        target_categories: List of COCO category names to include.

    Returns:
        Dictionary mapping original COCO category ID → new 0-indexed class ID.

    Raises:
        ValueError: If any target category is not found in COCO.
    """
    coco_cats = {cat["name"]: cat["id"] for cat in coco_api.loadCats(coco_api.getCatIds())}
    mapping: dict[int, int] = {}

    for idx, cat_name in enumerate(target_categories):
        if cat_name not in coco_cats:
            raise ValueError(
                f"Category '{cat_name}' not found in COCO. "
                f"Available: {sorted(coco_cats.keys())}"
            )
        mapping[coco_cats[cat_name]] = idx

    return mapping


def coco_bbox_to_yolo(
    bbox: list[float],
    image_width: int,
    image_height: int,
) -> list[float]:
    """Convert a COCO bbox [x_min, y_min, width, height] to YOLO format.

    YOLO format: [center_x, center_y, width, height] normalized to [0, 1].

    Args:
        bbox: COCO-format bounding box [x_min, y_min, w, h] in pixels.
        image_width: Width of the source image in pixels.
        image_height: Height of the source image in pixels.

    Returns:
        List of 4 floats in YOLO format [cx, cy, w, h], all in [0, 1].
    """
    x_min, y_min, box_w, box_h = bbox

    center_x = (x_min + box_w / 2.0) / image_width
    center_y = (y_min + box_h / 2.0) / image_height
    norm_w = box_w / image_width
    norm_h = box_h / image_height

    # Clamp to [0, 1] to handle edge cases
    center_x = max(0.0, min(1.0, center_x))
    center_y = max(0.0, min(1.0, center_y))
    norm_w = max(0.0, min(1.0, norm_w))
    norm_h = max(0.0, min(1.0, norm_h))

    return [center_x, center_y, norm_w, norm_h]


def filter_and_convert_coco_split(
    annotation_file: str,
    images_dir: str,
    output_images_dir: str,
    output_labels_dir: str,
    category_mapping: dict[int, int] | None = None,
    target_categories: list[str] | None = None,
    max_images: int | None = None,
    seed: int = 42,
) -> int:
    """Filter COCO annotations to target categories and convert to YOLO format.

    This function:
    1. Loads the COCO annotation JSON
    2. Finds images containing at least one target category
    3. Copies those images to the output directory
    4. Writes YOLO-format label .txt files alongside the images

    Args:
        annotation_file: Path to COCO annotation JSON (e.g., instances_train2017.json).
        images_dir: Path to the directory containing COCO images.
        output_images_dir: Destination directory for filtered images.
        output_labels_dir: Destination directory for YOLO label files.
        category_mapping: Optional pre-computed {coco_cat_id: yolo_class_id} mapping.
            If None, will be computed from target_categories.
        target_categories: List of COCO category names. Required if
            category_mapping is None.
        max_images: Maximum number of images to include (for Colab feasibility).
        seed: Random seed for reproducible subset selection.

    Returns:
        Number of images successfully processed.

    Raises:
        ValueError: If neither category_mapping nor target_categories is provided.
    """
    if category_mapping is None and target_categories is None:
        raise ValueError("Provide either category_mapping or target_categories.")

    coco = COCO(annotation_file)

    if category_mapping is None:
        category_mapping = get_coco_category_mapping(coco, target_categories)

    # Get all image IDs that contain at least one target category
    target_cat_ids = list(category_mapping.keys())
    image_ids: set[int] = set()
    for cat_id in target_cat_ids:
        image_ids.update(coco.getImgIds(catIds=[cat_id]))

    image_ids_list = sorted(image_ids)

    # Subsample if needed
    if max_images is not None and len(image_ids_list) > max_images:
        rng = np.random.default_rng(seed)
        image_ids_list = rng.choice(
            image_ids_list, size=max_images, replace=False
        ).tolist()

    os.makedirs(output_images_dir, exist_ok=True)
    os.makedirs(output_labels_dir, exist_ok=True)

    processed_count = 0

    for img_id in tqdm(image_ids_list, desc="Converting COCO → YOLO"):
        img_info = coco.loadImgs(img_id)[0]
        img_filename = img_info["file_name"]
        img_width = img_info["width"]
        img_height = img_info["height"]

        src_path = Path(images_dir) / img_filename
        if not src_path.exists():
            continue

        # Get annotations for this image, filtered to target categories
        ann_ids = coco.getAnnIds(imgIds=img_id, catIds=target_cat_ids, iscrowd=False)
        annotations = coco.loadAnns(ann_ids)

        if len(annotations) == 0:
            continue

        # Convert annotations to YOLO format
        yolo_lines: list[str] = []
        for ann in annotations:
            if ann["category_id"] not in category_mapping:
                continue
            if ann.get("iscrowd", 0):
                continue
            # Skip tiny bboxes (likely annotation noise)
            if ann["bbox"][2] < 2 or ann["bbox"][3] < 2:
                continue

            class_id = category_mapping[ann["category_id"]]
            yolo_bbox = coco_bbox_to_yolo(ann["bbox"], img_width, img_height)
            line = f"{class_id} {yolo_bbox[0]:.6f} {yolo_bbox[1]:.6f} {yolo_bbox[2]:.6f} {yolo_bbox[3]:.6f}"
            yolo_lines.append(line)

        if len(yolo_lines) == 0:
            continue

        # Copy image
        dst_img_path = Path(output_images_dir) / img_filename
        shutil.copy2(src_path, dst_img_path)

        # Write label file
        label_filename = Path(img_filename).stem + ".txt"
        label_path = Path(output_labels_dir) / label_filename
        with open(label_path, "w") as f:
            f.write("\n".join(yolo_lines) + "\n")

        processed_count += 1

    return processed_count


def apply_augmentations_to_dataset(
    images_dir: str,
    labels_dir: str,
    output_images_dir: str,
    output_labels_dir: str,
    augmentation_pipeline: A.Compose,
    num_augmented_per_image: int = 2,
) -> int:
    """Apply offline augmentations to expand the training set.

    For each original image, generates `num_augmented_per_image` augmented
    copies with transformed bounding boxes. Originals are also copied.

    Args:
        images_dir: Source directory of training images.
        labels_dir: Source directory of YOLO-format label files.
        output_images_dir: Destination for augmented images.
        output_labels_dir: Destination for augmented labels.
        augmentation_pipeline: Albumentations Compose with bbox support.
        num_augmented_per_image: How many augmented copies per original image.

    Returns:
        Total number of images in the augmented dataset (originals + augmented).
    """
    os.makedirs(output_images_dir, exist_ok=True)
    os.makedirs(output_labels_dir, exist_ok=True)

    image_files = sorted(Path(images_dir).glob("*.jpg"))
    total_count = 0

    for img_path in tqdm(image_files, desc="Augmenting"):
        label_path = Path(labels_dir) / (img_path.stem + ".txt")
        if not label_path.exists():
            continue

        image = cv2.imread(str(img_path))
        if image is None:
            continue
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Parse YOLO labels
        bboxes: list[list[float]] = []
        class_labels: list[int] = []
        with open(label_path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) != 5:
                    continue
                class_labels.append(int(parts[0]))
                bboxes.append([float(x) for x in parts[1:]])

        if len(bboxes) == 0:
            continue

        # Copy original
        dst_img = Path(output_images_dir) / img_path.name
        shutil.copy2(img_path, dst_img)
        shutil.copy2(label_path, Path(output_labels_dir) / label_path.name)
        total_count += 1

        # Generate augmented copies
        for aug_idx in range(num_augmented_per_image):
            try:
                transformed = augmentation_pipeline(
                    image=image,
                    bboxes=bboxes,
                    class_labels=class_labels,
                )
            except Exception:
                # Some augmentations can fail on edge-case images
                continue

            aug_bboxes = transformed["bboxes"]
            aug_classes = transformed["class_labels"]

            if len(aug_bboxes) == 0:
                continue

            # Save augmented image
            aug_filename = f"{img_path.stem}_aug{aug_idx}{img_path.suffix}"
            aug_img_path = Path(output_images_dir) / aug_filename
            aug_image_bgr = cv2.cvtColor(transformed["image"], cv2.COLOR_RGB2BGR)
            cv2.imwrite(str(aug_img_path), aug_image_bgr)

            # Save augmented labels
            aug_label_path = Path(output_labels_dir) / f"{img_path.stem}_aug{aug_idx}.txt"
            with open(aug_label_path, "w") as f:
                for cls_id, bbox in zip(aug_classes, aug_bboxes):
                    line = f"{cls_id} {bbox[0]:.6f} {bbox[1]:.6f} {bbox[2]:.6f} {bbox[3]:.6f}"
                    f.write(line + "\n")

            total_count += 1

    return total_count


def create_yolo_dataset_yaml(
    dataset_root: str,
    class_names: list[str],
    output_path: str | None = None,
) -> str:
    """Generate the dataset.yaml file required by Ultralytics YOLOv8.

    Args:
        dataset_root: Absolute path to the dataset root directory.
        class_names: Ordered list of class names (index = class ID).
        output_path: Where to write the YAML. Defaults to dataset_root/dataset.yaml.

    Returns:
        Path to the generated YAML file.
    """
    if output_path is None:
        output_path = str(Path(dataset_root) / "dataset.yaml")

    content = YOLO_DATASET_YAML_TEMPLATE.format(
        dataset_root=dataset_root,
        num_classes=len(class_names),
        class_names=json.dumps(class_names),
    )

    with open(output_path, "w") as f:
        f.write(content.strip() + "\n")

    return output_path


def prepare_dataset(config_path: str = "configs/default.yaml") -> str:
    """End-to-end dataset preparation: download, filter, convert, augment.

    This is the main entry point for data preparation. It orchestrates:
    1. Loading config
    2. Filtering COCO to target categories
    3. Converting to YOLO format
    4. Applying augmentations to training split
    5. Generating the dataset.yaml for Ultralytics

    NOTE: This function assumes COCO images and annotations have already been
    downloaded to the paths specified in config. For Colab, use the provided
    notebook which handles downloading via shell commands (much faster than
    Python HTTP for multi-GB files).

    Args:
        config_path: Path to the YAML configuration file.

    Returns:
        Path to the generated dataset.yaml file.
    """
    config = load_config(config_path)
    data_cfg = config["data"]

    coco_root = Path(data_cfg["coco_root"])
    target_categories = data_cfg["subset_categories"]
    max_train = data_cfg["max_train_images"]
    max_val = data_cfg["max_val_images"]
    seed = data_cfg["seed"]

    # Define paths
    train_ann = coco_root / "annotations" / "instances_train2017.json"
    val_ann = coco_root / "annotations" / "instances_val2017.json"
    train_images = coco_root / "train2017"
    val_images = coco_root / "val2017"

    dataset_root = Path("./datasets/yolo_defect")
    train_img_out = dataset_root / "images" / "train"
    train_lbl_out = dataset_root / "labels" / "train"
    val_img_out = dataset_root / "images" / "val"
    val_lbl_out = dataset_root / "labels" / "val"

    # Validate that COCO data exists
    for required_path in [train_ann, val_ann, train_images, val_images]:
        if not required_path.exists():
            raise FileNotFoundError(
                f"Required COCO path not found: {required_path}\n"
                f"Please download COCO 2017 to {coco_root}. See README for instructions."
            )

    print(f"[data_loader] Target categories: {target_categories}")
    print(f"[data_loader] Max train images: {max_train}, max val images: {max_val}")

    # --- Process training split ---
    print("\n[data_loader] Processing training split...")
    train_count = filter_and_convert_coco_split(
        annotation_file=str(train_ann),
        images_dir=str(train_images),
        output_images_dir=str(train_img_out),
        output_labels_dir=str(train_lbl_out),
        target_categories=target_categories,
        max_images=max_train,
        seed=seed,
    )
    print(f"[data_loader] Training images processed: {train_count}")

    # --- Process validation split ---
    print("\n[data_loader] Processing validation split...")
    val_count = filter_and_convert_coco_split(
        annotation_file=str(val_ann),
        images_dir=str(val_images),
        output_images_dir=str(val_img_out),
        output_labels_dir=str(val_lbl_out),
        target_categories=target_categories,
        max_images=max_val,
        seed=seed,
    )
    print(f"[data_loader] Validation images processed: {val_count}")

    # --- Apply augmentations (training only) ---
    print("\n[data_loader] Applying augmentations to training set...")
    aug_pipeline = build_augmentation_pipeline(config)
    augmented_train_img = dataset_root / "images" / "train_augmented"
    augmented_train_lbl = dataset_root / "labels" / "train_augmented"

    aug_count = apply_augmentations_to_dataset(
        images_dir=str(train_img_out),
        labels_dir=str(train_lbl_out),
        output_images_dir=str(augmented_train_img),
        output_labels_dir=str(augmented_train_lbl),
        augmentation_pipeline=aug_pipeline,
        num_augmented_per_image=2,
    )
    print(f"[data_loader] Augmented training set size: {aug_count}")

    # --- Generate dataset.yaml ---
    dataset_yaml_path = create_yolo_dataset_yaml(
        dataset_root=str(dataset_root.resolve()),
        class_names=target_categories,
    )
    print(f"\n[data_loader] Dataset YAML written to: {dataset_yaml_path}")
    print("[data_loader] Dataset preparation complete.")

    return dataset_yaml_path


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Prepare COCO subset for YOLOv8 defect detection training."
    )
    parser.add_argument(
        "--config",
        type=str,
        default="configs/default.yaml",
        help="Path to configuration YAML file.",
    )
    args = parser.parse_args()

    dataset_yaml = prepare_dataset(config_path=args.config)
    print(f"\nReady for training. Use dataset config: {dataset_yaml}")
